const translations={
 en:{from:'FROM',built:'BUILT FOR A',autoActivation:'IDENTITY SCAN / AUTO ACTIVATION',identityConfirmed:'IDENTITY CONFIRMED',welcomeTo:'WELCOME TO',moreThan:'MORE THAN SOLUTIONS.',wa:'Message IQ Group',explore:'EXPLORE OUR SERVICES',tapContinue:'SCROLL TO CONTINUE',whatWeDo:'WHAT WE DO',buildTitle:'WE BUILD<br><strong>WHAT THE IDEA NEEDS.</strong>',buildCopy:'Software, business systems, AI, websites, automation and digital experiences — designed as real products, not just concepts.',s1t:'SOFTWARE DEVELOPMENT',s1d:'Desktop, mobile and web applications built around the actual workflow.',s2t:'BUSINESS SYSTEMS',s2d:'Sales, inventory, subscriptions, administration, operations and custom workflows.',s3t:'AI & AUTOMATION',s3d:'AI assistants, intelligent features, automation and connected business processes.',s4t:'CLOUD & INTEGRATION',s4d:'Cloud backends, APIs, authentication, databases and third-party integrations.',s5t:'WEBSITES & DIGITAL EXPERIENCES',s5d:'High-impact websites, landing pages, QR experiences and digital interfaces.',s6t:'E-COMMERCE & RETAIL',s6d:'Retail platforms, products, pricing, warehouses, orders and customer experiences.',s7t:'CUSTOM PRODUCTS',s7d:'From a small tool to a complete production platform — architecture, build and delivery.',s8t:'CONSULTING & DIGITAL TRANSFORMATION',s8d:'We turn business problems and ideas into practical digital systems.',idea:'HAVE AN IDEA?',letsBuild:"LET'S BUILD IT.",ctaCopy:'Tell us what you need. We design the system, build it and turn it into something you can actually use.',talk:'TALK TO IQ GROUP ↗'},
 ar:{from:'من',built:'مصمم من أجل',autoActivation:'فحص الهوية / تفعيل تلقائي',identityConfirmed:'تم تأكيد الهوية',welcomeTo:'أهلاً بك في',moreThan:'أكثر من مجرد حلول.',wa:'تواصل مع IQ Group',explore:'استكشف خدماتنا',tapContinue:'اسحب للاستمرار',whatWeDo:'ماذا نقدم',buildTitle:'نبني<br><strong>ما تحتاجه فكرتك.</strong>',buildCopy:'برمجيات، أنظمة أعمال، ذكاء اصطناعي، مواقع، أتمتة وتجارب رقمية — منتجات حقيقية مصممة للاستخدام الفعلي، وليست مجرد أفكار.',s1t:'تطوير البرمجيات',s1d:'تطبيقات سطح مكتب وموبايل وويب مبنية حول طريقة عملك الفعلية.',s2t:'أنظمة الأعمال',s2d:'المبيعات والمخزون والاشتراكات والإدارة والعمليات وسير العمل المخصص.',s3t:'الذكاء الاصطناعي والأتمتة',s3d:'مساعدات ذكية، خصائص AI، أتمتة وربط العمليات التجارية.',s4t:'السحابة والتكامل',s4d:'خدمات سحابية وواجهات API وقواعد بيانات وتوثيق وربط الأنظمة الخارجية.',s5t:'المواقع والتجارب الرقمية',s5d:'مواقع وصفحات هبوط وتجارب QR وواجهات رقمية عالية التأثير.',s6t:'التجارة الإلكترونية والريتيل',s6d:'منصات البيع والمنتجات والأسعار والمخازن والطلبات وتجربة العملاء.',s7t:'منتجات مخصصة',s7d:'من أداة صغيرة إلى منصة إنتاج متكاملة — تحليل وهندسة وبناء وتسليم.',s8t:'الاستشارات والتحول الرقمي',s8d:'نحوّل مشاكل الأعمال والأفكار إلى أنظمة رقمية عملية.',idea:'عندك فكرة؟',letsBuild:'خلينا نبنيها.',ctaCopy:'احچي لنا شتحتاج. نصمم النظام ونبنيه ونحوّله إلى شيء فعلي تقدر تستخدمه.',talk:'تواصل مع IQ Group ↗'}
};
function setLanguage(lang){const t=translations[lang]||translations.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key]!==undefined)el.innerHTML=t[key]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('iqgroup-lang',lang)}
const params=new URLSearchParams(location.search);const browser=(navigator.language||'en').toLowerCase();let lang=params.get('lang')||localStorage.getItem('iqgroup-lang')||(browser.startsWith('ar')?'ar':'en');setLanguage(lang);
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
window.addEventListener('load',()=>{setTimeout(()=>document.getElementById('loader').classList.add('done'),900);setTimeout(()=>{document.getElementById('identityPanel').classList.add('reveal');document.getElementById('quickLinks').classList.add('reveal')},2100)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in') }),{threshold:.12});document.querySelectorAll('.service,.products,.cta').forEach(x=>observer.observe(x));
